/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-02-15 04:59:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import gall.Search;
import java.net.InetAddress;
import gall.SearchDao;
import java.util.Collections;
import java.util.Stack;
import java.util.ArrayList;
import gall.GallListDao;
import gall.GallList;
import java.util.List;

public final class createMinorForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/header.jsp", Long.valueOf(1676425068561L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.InetAddress");
    _jspx_imports_classes.add("gall.GallListDao");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("gall.SearchDao");
    _jspx_imports_classes.add("gall.GallList");
    _jspx_imports_classes.add("java.util.Collections");
    _jspx_imports_classes.add("java.util.Stack");
    _jspx_imports_classes.add("gall.Search");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	main {width: 960px; margin: 20px auto 0;}\r\n");
      out.write("	main > h2 { margin-bottom: 10px;}\r\n");
      out.write("	\r\n");
      out.write("	h2 a {cursor: pointer;}\r\n");
      out.write("	\r\n");
      out.write("	footer {\r\n");
      out.write("		padding-bottom: 50px;\r\n");
      out.write("		font-size: 12px;\r\n");
      out.write("	}\r\n");
      out.write("	footer > div:first-of-type {\r\n");
      out.write("		width: 1050px;\r\n");
      out.write("	    margin: 0px auto 0;\r\n");
      out.write("	    padding-top: 28px;\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	footer > div a:before {\r\n");
      out.write("	    content: \"\";\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	    width: 1px;\r\n");
      out.write("	    height: 11px;\r\n");
      out.write("	    margin: 0 10px;\r\n");
      out.write("	    vertical-align: -1px;\r\n");
      out.write("	    background: #d7d7d7;\r\n");
      out.write("	}\r\n");
      out.write("	footer > div a:first-child:before {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	footer > div:last-of-type {\r\n");
      out.write("	    width: 1050px;\r\n");
      out.write("	    margin: 10px auto 0;\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	    letter-spacing: 0;\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("	    font-family: tahoma,sans-serif;\r\n");
      out.write("	    color: #333;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.main_color {color: #d2af8a;}\r\n");
      out.write("	.sub_color {color: #585857;}\r\n");
      out.write("	.small {font-size: 13px; color: #999; font-weight: bold; margin-left: 6px;}\r\n");
      out.write("	\r\n");
      out.write("	.border {border-top: 2px #d2af8a solid; border-bottom: 2px #d2af8a solid;}\r\n");
      out.write("	.border > h2 {font-size: 23px; color: #d31900; margin-top: 41px; padding-left: 69px;}\r\n");
      out.write("	.border > p {font-size: 17px; color: #222; font-weight: bold; margin: 5px 0 33px; padding-left: 69px;}\r\n");
      out.write("	\r\n");
      out.write("	.info {\r\n");
      out.write("		width: 411px;\r\n");
      out.write("	    padding: 19px 22px;\r\n");
      out.write("	    margin: 34px 0 34px 69px;\r\n");
      out.write("	    background: #f3f3f3;\r\n");
      out.write("	    border-radius: 2px;\r\n");
      out.write("	    line-height: 20px;\r\n");
      out.write("	    color: #555;\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("	    letter-spacing: -0.05em;\r\n");
      out.write("	}\r\n");
      out.write("	.info > div:last-of-type {margin-top: 12px;}\r\n");
      out.write("	.info button {\r\n");
      out.write("		text-decoration: underline;\r\n");
      out.write("	    color: #d31900;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	    background: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .label {\r\n");
      out.write("    	width: 130px;\r\n");
      out.write("	    float: left;\r\n");
      out.write("	}\r\n");
      out.write("	.label span {\r\n");
      out.write("	    padding-left: 3px;\r\n");
      out.write("	    color: #d31900;\r\n");
      out.write("    }\r\n");
      out.write("    .label label {font-weight: bold;}\r\n");
      out.write("	\r\n");
      out.write("	.abs {\r\n");
      out.write("		position: absolute;\r\n");
      out.write("	    right: 9px;\r\n");
      out.write("	    top: 4px;\r\n");
      out.write("	    color: #d2af8a;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.fl {float: left;}\r\n");
      out.write("    .fl p {color: #d31900; font-weight: normal;}\r\n");
      out.write("    .fl textarea {\r\n");
      out.write("	    width: 470px;\r\n");
      out.write("	    height: 54px;\r\n");
      out.write("	    padding: 7px;\r\n");
      out.write("	    border: 1px #bbb solid;\r\n");
      out.write("	    margin-bottom: 5px;\r\n");
      out.write("	    resize: none;\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("	    font-family: -apple-system,BlinkMacSystemFont,\"Apple SD Gothic Neo\",\"Malgun Gothic\",\"맑은 고딕\",arial,Dotum,돋움,sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    .fl .bl {color: #555;}\r\n");
      out.write("    \r\n");
      out.write("    .fr {float: right;}\r\n");
      out.write("    \r\n");
      out.write("    .input_box {\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .ex {\r\n");
      out.write("    	width: 241px;\r\n");
      out.write("    	opacity: 0.7;\r\n");
      out.write("    	margin-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .ex textarea {\r\n");
      out.write("	    width: 225px;\r\n");
      out.write("	    color: #999;\r\n");
      out.write("	    height: 54px;\r\n");
      out.write("	    padding: 7px;\r\n");
      out.write("	    border: 1px #bbb solid;\r\n");
      out.write("	    margin-bottom: 5px;\r\n");
      out.write("	    resize: none;\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("	    font-family: -apple-system,BlinkMacSystemFont,\"Apple SD Gothic Neo\",\"Malgun Gothic\",\"맑은 고딕\",arial,Dotum,돋움,sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    .ex > span {\r\n");
      out.write("    	color: #555;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .tiptxt {\r\n");
      out.write("	    color: #555;\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("    	margin-left: 3px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.tip_deco_dot {\r\n");
      out.write("	    content: \"\";\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	    width: 2px;\r\n");
      out.write("	    height: 2px;\r\n");
      out.write("	    background: #333;\r\n");
      out.write("	    font-size: 0;\r\n");
      out.write("	    vertical-align: 4px;\r\n");
      out.write("	    margin-right: 6px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.btnbox {\r\n");
      out.write("	    margin: 42px 0 86px;\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.btnbox button {\r\n");
      out.write("		width: 100px;\r\n");
      out.write("		height: 40px;\r\n");
      out.write("	    border-width: 1px 1px 3px 1px;\r\n");
      out.write("	    border-style: solid;\r\n");
      out.write("	    border-radius: 2px;\r\n");
      out.write("	    font-size: 14px;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	    color: #fff;\r\n");
      out.write("	}\r\n");
      out.write("    \r\n");
      out.write("    #left {\r\n");
      out.write("	    width: 726px;\r\n");
      out.write("	    padding: 12px 0 2px;\r\n");
      out.write("    	display: table-cell;\r\n");
      out.write("    	color: #555;\r\n");
      out.write("    	font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    #left > div {\r\n");
      out.write("    	padding: 13px 0 14px 16px;\r\n");
      out.write("	    border-top: 1px #eee solid;\r\n");
      out.write("	    color: #555;\r\n");
      out.write("	    position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    #left > div::after {\r\n");
      out.write("	    clear: both;\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    visibility: hidden;\r\n");
      out.write("	    content: \"\";\r\n");
      out.write("    }\r\n");
      out.write("    #left > div:first-of-type {border: none; padding-top: 2px;}\r\n");
      out.write("    #left input:not([type=file]) {\r\n");
      out.write("	    color: #555;\r\n");
      out.write("	    height: 22px;\r\n");
      out.write("	    line-height: 20px;\r\n");
      out.write("	    border: 1px #bbb solid;\r\n");
      out.write("	    margin-bottom: 5px;\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #right {\r\n");
      out.write("	    width: 288px;\r\n");
      out.write("	    padding: 14px 21px 2px 15px;\r\n");
      out.write("	    background: #f3f3f3;\r\n");
      out.write("    	display: table-cell;\r\n");
      out.write("    	vertical-align: top;\r\n");
      out.write("    	font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    #right p {\r\n");
      out.write("	    padding-top: 5px;\r\n");
      out.write("	    color: #d31900;\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #name {\r\n");
      out.write("	    width: 250px;\r\n");
      out.write("	    padding: 0 92px 0 7px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #addr {\r\n");
      out.write("	    padding: 0 7px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #why {\r\n");
      out.write("    	width: 428px;\r\n");
      out.write("    	padding: 0 7px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #ex_name {\r\n");
      out.write("	    width: 140px;\r\n");
      out.write("	    color: #999;\r\n");
      out.write("	    padding: 0 92px 0 7px;\r\n");
      out.write("	    height: 22px;\r\n");
      out.write("	    border: 1px #bbb solid;\r\n");
      out.write("	    margin-bottom: 5px;\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #bot {\r\n");
      out.write("    	padding-top: 24px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #cancel {\r\n");
      out.write("	    background: #b2b4b2;\r\n");
      out.write("	    border-color: #b2b4b2;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #make {\r\n");
      out.write("	    background: #d2af8a;\r\n");
      out.write("	    border-color: #d2af8a;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#name\").on(\"keyup\", function() {\r\n");
      out.write("			let content = $(this).val()\r\n");
      out.write("			$(\"#nn\").text(content.length)\r\n");
      out.write("			if (content.length > 12) {\r\n");
      out.write("				$(this).val(content.substring(0, 12))\r\n");
      out.write("				$('#nn').text(12)\r\n");
      out.write("			}\r\n");
      out.write("	    });\r\n");
      out.write("		\r\n");
      out.write("		$(\"#desc\").on(\"keyup\", function() {\r\n");
      out.write("			let content = $(this).val()\r\n");
      out.write("			$(\"#dn\").text(content.length)\r\n");
      out.write("			if (content.length > 200) {\r\n");
      out.write("				$(this).val(content.substring(0, 200))\r\n");
      out.write("				$('#dn').text(200)\r\n");
      out.write("			}\r\n");
      out.write("	    });\r\n");
      out.write("		\r\n");
      out.write("		$(\"#addr\").on(\"keyup\", function() {\r\n");
      out.write("			let content = $(this).val()\r\n");
      out.write("			$(\"#an\").text(content.length)\r\n");
      out.write("			if (content.length > 20) {\r\n");
      out.write("				$(this).val(content.substring(0, 20))\r\n");
      out.write("				$('#an').text(20)\r\n");
      out.write("			}\r\n");
      out.write("	    });\r\n");
      out.write("		\r\n");
      out.write("		$(\"#why\").on(\"keyup\", function() {\r\n");
      out.write("			let content = $(this).val()\r\n");
      out.write("			$(\"#wn\").text(content.length)\r\n");
      out.write("			if (content.length > 100) {\r\n");
      out.write("				$(this).val(content.substring(0, 100))\r\n");
      out.write("				$('#wn').text(100)\r\n");
      out.write("			}\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function input_check() {\r\n");
      out.write("		let name = document.getElementById(\"name\")\r\n");
      out.write("		let cate = document.getElementById(\"cate\")\r\n");
      out.write("		let why = document.getElementById(\"why\")\r\n");
      out.write("		\r\n");
      out.write("		if (!name.value) {\r\n");
      out.write("		    alert(\"이름을 입력하세요.\")\r\n");
      out.write("		    name.focus()\r\n");
      out.write("		    return false\r\n");
      out.write("		}\r\n");
      out.write("		if (cate.value == 'null') {\r\n");
      out.write("		    alert(\"카테고리를 선택하세요.\")\r\n");
      out.write("		    cate.focus()\r\n");
      out.write("		    return false\r\n");
      out.write("		}\r\n");
      out.write("		if (!why.value) {\r\n");
      out.write("		    alert(\"개설이유를 입력하세요.\")\r\n");
      out.write("		    why.focus()\r\n");
      out.write("		    return false\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		document.create.submit()\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String word = "";
	if(request.getParameter("word") != null)
		word = request.getParameter("word");
	
	String ip = request.getRemoteAddr();
	if(ip.equalsIgnoreCase("0:0:0:0:0:0:0:1")){
	    InetAddress inetAddress = InetAddress.getLocalHost();
	    ip = inetAddress.getHostAddress();
	}
	
	ArrayList<String> viList = (ArrayList)session.getAttribute("visitList");
	ArrayList<Search> sList = SearchDao.getInstance().select(ip);
	
	String save = (String)session.getAttribute("save");
	if(save == null)
		save = "on";

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	* {margin: 0; padding: 0;}\r\n");
      out.write("	a {text-decoration: none; color: black;}\r\n");
      out.write("	a:not(h1 a,h4 a,h5 a,h2 a):hover {text-decoration: underline;}\r\n");
      out.write("	\r\n");
      out.write("	header {margin-top: 30px; position: relative; }\r\n");
      out.write("	button {cursor: pointer;}\r\n");
      out.write("	h1 {display: inline-block; margin-right: 5%;}\r\n");
      out.write("	\r\n");
      out.write("	nav {background: /* #c9b18c */ #d2af8a; width: 100%; padding: 10px; margin-top: 20px; color: white;}\r\n");
      out.write("	nav ul {margin: 0 auto; width: 950px;}\r\n");
      out.write("	nav li {display: inline-block; margin-right: 15px; font-weight: bold;}\r\n");
      out.write("	nav a {color: white;}\r\n");
      out.write("	\r\n");
      out.write("	#search {display: inline-block; border: 4px solid #d2af8a; height: 39px;}\r\n");
      out.write("	#search input[type=text] {width: 315px; height: 35px; float: left; padding: 2px 9px 0; outline: none; border: none; font-weight: bold; color: #333; font-size: 14px;}\r\n");
      out.write("	#search input::placeholder {color: #b2b4b2;}\r\n");
      out.write("	#search form button {width: 40px; height: 40px; background: #d2af8a; border: none;}\r\n");
      out.write("	#search img {width: 25px;}\r\n");
      out.write("	#search h5 {background: #f3f3f3; padding: 10px 12px; display: block; color: #d2af8a;}\r\n");
      out.write("	#search h5 button {position: absolute; top: 5px; right: 4px; color: #999; text-decoration: underline; border: none; font-size: 12px; padding: 5px;}\r\n");
      out.write("	#search > div {position: absolute; border: 2px solid #d2af8a; background: #fff; width: 377px; left: 40%; display: none;}\r\n");
      out.write("	#search ul {list-style: none; padding: 8px 0;}\r\n");
      out.write("	#search ul img {width: 8px;}\r\n");
      out.write("	#search ul a {display: block; color: #555; text-decoration: none; height: 27px;}\r\n");
      out.write("	#search ul button {position: absolute; right: 12px; top: 5px; border: none; background: none;}\r\n");
      out.write("	#search li {position: relative; padding: 0 25px 0 12px;}\r\n");
      out.write("	#search li:hover {background: #f3f3f3;}\r\n");
      out.write("	\r\n");
      out.write("	#save {border-top: 1px #d2af8a solid; color: #d2af8a; font-size: 13px; padding: 10px;}\r\n");
      out.write("	#save img {position: absolute;}\r\n");
      out.write("	#save button {border: none; background: none; color: #d2af8a; font-size: 13px; }\r\n");
      out.write("	#save button img {width: 36px; bottom: 1px; left: 85px;}\r\n");
      out.write("	#save > img {width: 15px; right: 10px; cursor: pointer;}\r\n");
      out.write("\r\n");
      out.write("	#visit {margin: 0 auto; width: 930px; border: 1px solid gainsboro; padding: 10px; font-size: 12px; color: #d2af8a; font-weight: bold; background-color: rgb(240, 240, 240);}\r\n");
      out.write("    #visit img {height: 8px; cursor: pointer;}\r\n");
      out.write("    #visit button {background-color: white; padding: 0 4px; border: 1px solid gainsboro; margin: 0 5px; cursor: pointer;}\r\n");
      out.write("    #visit li,#visit ul {display: inline;}\r\n");
      out.write("    #visit a {color: black; font-weight: normal;}\r\n");
      out.write("    #visit ul img {margin: 0 10px; height: 7px; cursor: pointer;}\r\n");
      out.write("    #visit ul {margin-left: 5px;}\r\n");
      out.write("    \r\n");
      out.write("    #empty {font-size: 12px; color: #999; text-align: center; padding: 100px 0;}\r\n");
      out.write("    #top {\r\n");
      out.write("	    width: 950px;\r\n");
      out.write("	    margin: 0 auto;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .right {float: right;}\r\n");
      out.write("	.left {float: left;}\r\n");
      out.write("	.main_color {color: #d2af8a;}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	if(sessionStorage.getItem(\"save\") == \"on\") {\r\n");
      out.write("		$(\"#save button img\").attr(\"src\",\"image/switch.png\")\r\n");
      out.write("	}\r\n");
      out.write("	else if(sessionStorage.getItem(\"save\") == \"off\") {\r\n");
      out.write("		$(\"#save button img\").attr(\"src\",\"image/switch3.png\")\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#search input\").on(\"click\", function() {\r\n");
      out.write("			if($(\"#save button img\").attr(\"src\") === \"image/switch.png\")\r\n");
      out.write("	    		$(\"#search > div\").show()\r\n");
      out.write("	    });\r\n");
      out.write("	    \r\n");
      out.write("	    $(\"#save > img\").on(\"click\", function() {\r\n");
      out.write("	    	$(\"#search > div\").hide()\r\n");
      out.write("	    });\r\n");
      out.write("	    \r\n");
      out.write("	    $(\"#search input\").on(\"keyup\", function() {\r\n");
      out.write("	    	if($(\"#search input\").val())\r\n");
      out.write("	    		$(\"#search > div\").show()\r\n");
      out.write("	    	else\r\n");
      out.write("		    	$(\"#search > div\").hide()\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function check() {\r\n");
      out.write("		if($(\"#save button img\").attr(\"src\") === \"image/switch.png\") {\r\n");
      out.write("			if(confirm(\"검색어 저장 기능을 중지하시겠습니까?\")) {\r\n");
      out.write("				$(\"#search > div\").hide()\r\n");
      out.write("				$(\"#save button img\").attr(\"src\",\"image/switch3.png\")\r\n");
      out.write("				$(\"#search input[name=save]\").attr(\"value\",\"off\")\r\n");
      out.write("				location.href=\"searchSave.jsp?save=off\"\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		else {\r\n");
      out.write("			if(confirm(\"검색어 저장 기능을 사용하시겠습니까?\")) {\r\n");
      out.write("				$(\"#search > div\").show()\r\n");
      out.write("				$(\"#save button img\").attr(\"src\",\"image/switch.png\")\r\n");
      out.write("				$(\"#search input[name=save]\").attr(\"value\",\"on\")\r\n");
      out.write("				location.href=\"searchSave.jsp?save=on\"\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function delCheck() {\r\n");
      out.write("		if(confirm(\"검색 목록을 모두 삭제하시겠습니까?\"))\r\n");
      out.write("			location.href='delSearch.jsp?del=all'\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<header>\r\n");
      out.write("	<div id=top>\r\n");
      out.write("		<h1><a href=main.jsp>minami.com</a></h1>\r\n");
      out.write("		<div id=search>\r\n");
      out.write("			<form action=\"search.jsp\" autocomplete=\"off\">\r\n");
      out.write("				<input type=text placeholder=\"게시판 & 통합검색\" name=\"word\" value=");
      out.print( word );
      out.write(">\r\n");
      out.write("				<input type=hidden value=");
      out.print(save);
      out.write(" name=save>\r\n");
      out.write("				<button><img src=\"image/search2.png\"></button>\r\n");
      out.write("			</form>\r\n");
      out.write("			<div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<h5>최근 검색어<button onclick=delCheck()>전체 삭제</button></h5>\r\n");
      out.write("					");

						if(sList.size() == 0) {
							
      out.write("<div id=empty>최근 검색어가 없습니다.</div>");

						}
						else {
							
      out.write("<ul>");

							for(int i = sList.size()-1; i >= 0; i--) {
								
      out.write("<li><a href=\"search.jsp?word=");
      out.print( sList.get(i).getWord() );
      out.write("&save=");
      out.print(save);
      out.write('"');
      out.write('>');
      out.print(sList.get(i).getWord() );
      out.write("</a>\r\n");
      out.write("									<button onclick=\"location.href='delSearch.jsp?idx=");
      out.print(sList.get(i).getIdx());
      out.write("'\"><img src=image/x1.png></button>");

							}
							
      out.write("</ul>");

						}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=save>\r\n");
      out.write("					<button onclick=check()><b>검색어 저장</b>\r\n");
      out.write("					");

						if(save.equals("on")) {
							
      out.write("<img src=image/switch.png>");

						}
						else {
							
      out.write("<img src=image/switch3.png>");

						}
					
      out.write("</button>\r\n");
      out.write("					<img src=image/close2.png>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=#>메인</a>\r\n");
      out.write("			<li><a href=minor.jsp id=minor>마이너</a>\r\n");
      out.write("			<li><a href=#>미니</a>\r\n");
      out.write("			<li>|\r\n");
      out.write("			<li><a href=#>블로그</a>\r\n");
      out.write("			<li><a href=#>뉴스</a>\r\n");
      out.write("			<li><a href=#>게임</a>\r\n");
      out.write("			<li><a href=#>위키</a>\r\n");
      out.write("			<li><a href=#>이벤트</a>\r\n");
      out.write("			<li><a href=#>이모티콘</a>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<div id=visit>\r\n");
      out.write("		최근 방문\r\n");
      out.write("        <button><img src=\"image/drop-down-arrow2.png\"></button>\r\n");
      out.write("        <img src=\"image/left.png\">\r\n");
      out.write("        <ul>\r\n");
      out.write("        ");

        	if (viList != null) {
        		for (int i = viList.size()-1; i >= 0; i--) {
        			int index = GallListDao.getInstance().selectIdx(viList.get(i));
            		
      out.write("<li><a href=\"gallMain.jsp?idx=");
      out.print(index );
      out.write('"');
      out.write('>');
      out.print( viList.get(i) );
      out.write("</a>\r\n");
      out.write("            		");

            			if (request.getQueryString() == null) {
            				
      out.write("<img src=\"image/x1.png\" onclick=\"location.href='delVisit.jsp?gall=");
      out.print( viList.get(i) );
      out.write("&url=");
      out.print(request.getRequestURL());
      out.write('\'');
      out.write('"');
      out.write('>');

            			}
            			else {
            				
      out.write("<img src=\"image/x1.png\" onclick=\"location.href='delVisit.jsp?gall=");
      out.print( viList.get(i) );
      out.write("&url=");
      out.print(request.getRequestURL()+"?"+request.getQueryString() );
      out.write('\'');
      out.write('"');
      out.write('>');

            			}
            	}
        	}
        
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"right\"><img src=\"image/right-arrow.png\"><a href=\"#\">전체</a></div>\r\n");
      out.write("	 </div>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("	if(document.location.href.indexOf(\"minor.jsp\") != -1)\r\n");
      out.write("		$(\"#minor\").css(\"color\", \"#ffed44\")\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<h2><a class=main_color><span class=sub_color>마이너 게시판</span> 만들기</a><span class=small>(만들기는 6개까지 가능합니다.)</span></h2>\r\n");
      out.write("		<div class=border>\r\n");
      out.write("			<h2>마이너 게시판은?</h2>\r\n");
      out.write("			<p>누구나 게시판을 개설할 수 있습니다. 게시판의 운영 권한 및 의무가 개설자에게 부여됩니다.</p>\r\n");
      out.write("			<div class=info>\r\n");
      out.write("				<div>\r\n");
      out.write("					<strong class=\"main_color\">승격 안내</strong>\r\n");
      out.write("					<p>영화, 드라마 등 일부 마이너 게시판은 심사 후 메인 게시판으로 승격됩니다.</p>\r\n");
      out.write("					<p>승격 여부는 전적으로 회사에 의해 결정되며, 승격 시 매니저 권한은 회수됩니다.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<strong class=\"main_color\">유의 사항</strong>\r\n");
      out.write("					<p>메인 게시판 승격을 위해서는 간결하고 정확한 단어형 이름을 입력하셔야 합니다.</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						동일한 주제의 메인 게시판이 있을 경우 승격이 불가능합니다.\r\n");
      out.write("						<button type=\"button\">자세히보기</button>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form action=createMinor.jsp method=post id=create name=create enctype=\"multipart/form-data\">\r\n");
      out.write("				<div class=border>\r\n");
      out.write("					<div id=left>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=label><label for=name>이름<span>*</span></label></div>\r\n");
      out.write("							<div class=fl>\r\n");
      out.write("								<div class=input_box>\r\n");
      out.write("									<input id=name type=text name=name placeholder=\"마이너 게시판 이름을 간단히 넣어주세요.\">\r\n");
      out.write("									<span class=abs>마이너 게시판</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<span id=nn>0</span>/<b>12</b>\r\n");
      out.write("								<p>※ 이름은 개설 후, 7일 내 1회만 수정할 수 있습니다.</p>\r\n");
      out.write("								<p>※ 동일한 주제의 마이너 게시판은 개설이 불가능합니다.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=label><label for=desc>설명</label></div>\r\n");
      out.write("							<div class=fl>\r\n");
      out.write("								<textarea id=desc name=desc placeholder=\"마이너 게시판에 대한 설명을 넣어주세요.\"></textarea>\r\n");
      out.write("								<div><span class=fr><span id=dn>0</span>/<b>200</b></span></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=label><label for=image>대표 이미지</label></div>\r\n");
      out.write("							<div class=fl>\r\n");
      out.write("								<input id=image type=file name=image>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=label><label for=cate>카테고리<span>*</span></label></div>\r\n");
      out.write("							<div class=fl>\r\n");
      out.write("								<select id=cate name=cate>\r\n");
      out.write("									<option value=null>카테고리를 선택해주세요.\r\n");
      out.write("									<option>게임\r\n");
      out.write("									<option>취미\r\n");
      out.write("									<option>스포츠\r\n");
      out.write("									<option>디지털/IT\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=label><label for=why>개설이유<span>*</span></label></div>\r\n");
      out.write("							<div class=fl>\r\n");
      out.write("								<input id=why type=text name=why placeholder=\"운영자에게 전달되는 메세지입니다.\">\r\n");
      out.write("								<span id=wn>0</span>/<b>100</b>\r\n");
      out.write("								<p class=bl>※ 마이너 게시판 개설은 이름, 설명, 주소, 개설 이유에 따라 승인 또는 반려될 수 있습니다.</p>\r\n");
      out.write("								<p class=bl>※ 개설 승인, 반려는 평일 정상근무 시간에 처리됩니다.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=right>\r\n");
      out.write("						<p class=fl>예시</p>\r\n");
      out.write("						<div class=\"fr ex\">\r\n");
      out.write("							<div class=input_box>\r\n");
      out.write("								<input id=ex_name type=text value=\"백수\" readonly=\"readonly\">\r\n");
      out.write("								<span class=abs>마이너 게시판</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<textarea readonly=\"readonly\">백수, 백조 모두 모두 모여요.</textarea>\r\n");
      out.write("							<span class=fr><span>17</span>/<b>200</b></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			<div id=bot>\r\n");
      out.write("				<p class=\"tiptxt\">\r\n");
      out.write("					<em class=\"tip_deco_dot\"></em>게시물의 관리 의무와 권리는 매니저(개설자)에게 있으며, 운영원칙을 위반한 경우 폐쇄 또는 매니저 해임이 될 수 있습니다.(음란물, 불량 게시물, 상업적 게시물, 댓글의 방치 등)\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"btnbox\">\r\n");
      out.write("				<button type=\"button\" id=\"cancel\" onclick=\"history.back()\">취소</button>\r\n");
      out.write("				<button type=\"button\" id=\"make\" onclick=input_check()>만들기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("	<footer>\r\n");
      out.write("	    <div>\r\n");
      out.write("	      <a href=>회사소개</a>\r\n");
      out.write("	      <a href=>제휴안내</a>\r\n");
      out.write("	      <a href=>광고안내</a>\r\n");
      out.write("	      <a href=>이용약관</a>\r\n");
      out.write("	      <a href=><b>개인정보처리방침</b></a>\r\n");
      out.write("	      <a href=>청소년보호정책</a>\r\n");
      out.write("	      <a href=>마이너 게시판 운영원칙</a>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div>Copyright ⓒ 1999 - 2023 minami. All rights reserved.</div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
